    { SDLK_TAB,			"Tab"		},
    { SDLK_BACKSPACE,		"Backspace"	},
    { SDLK_CLEAR,		"Clear"		},
    { SDLK_RETURN,		"Return"	},
    { SDLK_PAUSE,		"Pause"		},
    { SDLK_ESCAPE,		"Escape"	},
    { SDLK_SPACE,		"Space"		},
    { SDLK_EXCLAIM,		"!"		},
    { SDLK_QUOTEDBL,		"\""		},
    { SDLK_HASH,		 "#"		},
    { SDLK_DOLLAR,		"$"		},
    { SDLK_AMPERSAND,		 "&"		},
    { SDLK_QUOTE,		"'"		},
    { SDLK_LEFTPAREN,		"("		},
    { SDLK_RIGHTPAREN,		")"		},
    { SDLK_ASTERISK,		"*"		},
    { SDLK_PLUS,		"+"		},
    { SDLK_COMMA,		","		},
    { SDLK_MINUS,		"-"		},
    { SDLK_PERIOD,		"."		},
    { SDLK_SLASH,		"/"		},
    { SDLK_BACKQUOTE,		"`"		},
    { SDLK_0,			"0"		},
    { SDLK_1,			"1"		},
    { SDLK_2,			"2"		},
    { SDLK_3,			"3"		},
    { SDLK_4,			"4"		},
    { SDLK_5,			"5"		},
    { SDLK_6,			"6"		},
    { SDLK_7,			"7"		},
    { SDLK_8,			"8"		},
    { SDLK_9,			"9"		},
    { SDLK_COLON,		":"		},
    { SDLK_SEMICOLON,		";"		},
    { SDLK_LESS,		"<"		},
    { SDLK_EQUALS,		"="		},
    { SDLK_GREATER,		">"		},
    { SDLK_QUESTION,		"?"		},
    { SDLK_AT,			"@"		},
    { SDLK_LEFTBRACKET,		"["		},
    { SDLK_BACKSLASH,		"\\"		},
    { SDLK_RIGHTBRACKET,	"]"		},
    { SDLK_CARET,		"^"		},
    { SDLK_UNDERSCORE,		"_"		},
    { SDLK_a,			"a"		},
    { SDLK_b,			"b"		},
    { SDLK_c,			"c"		},
    { SDLK_d,			"d"		},
    { SDLK_e,			"e"		},
    { SDLK_f,			"f"		},
    { SDLK_g,			"g"		},
    { SDLK_h,			"h"		},
    { SDLK_i,			"i"		},
    { SDLK_j,			"j"		},
    { SDLK_k,			"k"		},
    { SDLK_l,			"l"		},
    { SDLK_m,			"m"		},
    { SDLK_n,			"n"		},
    { SDLK_o,			"o"		},
    { SDLK_p,			"p"		},
    { SDLK_q,			"q"		},
    { SDLK_r,			"r"		},
    { SDLK_s,			"s"		},
    { SDLK_t,			"t"		},
    { SDLK_u,			"u"		},
    { SDLK_v,			"v"		},
    { SDLK_w,			"w"		},
    { SDLK_x,			"x"		},
    { SDLK_y,			"y"		},
    { SDLK_z,			"z"		},
    { SDLK_KP0,			"KP0"		},
    { SDLK_KP1,			"KP1"		},
    { SDLK_KP2,			"KP2"		},
    { SDLK_KP3,			"KP3"		},
    { SDLK_KP4,			"KP4"		},
    { SDLK_KP5,			"KP5"		},
    { SDLK_KP6,			"KP6"		},
    { SDLK_KP7,			"KP7"		},
    { SDLK_KP8,			"KP8"		},
    { SDLK_KP9,			"KP9"		},
    { SDLK_KP_PERIOD,		"KP."		},
    { SDLK_KP_DIVIDE,		"KP/"		},
    { SDLK_KP_MULTIPLY,		"KP*"		},
    { SDLK_KP_MINUS,		"KP-"		},
    { SDLK_KP_PLUS,		"KP+"		},
    { SDLK_KP_ENTER,		"Enter"		},
    { SDLK_KP_EQUALS,		"KP="		},
    { SDLK_UP,			"Up"		},
    { SDLK_DOWN,		"Down"		},
    { SDLK_RIGHT,		"Right"		},
    { SDLK_LEFT,		"Left"		},
    { SDLK_INSERT,		"Insert"	},
    { SDLK_DELETE,		"Delete"	},
    { SDLK_HOME,		"Home"		},
    { SDLK_END,			"End"		},
    { SDLK_PAGEUP,		"PgUp"		},
    { SDLK_PAGEDOWN,		"PgDown"	},
    { SDLK_F1,			"F1"		},
    { SDLK_F2,			"F2"		},
    { SDLK_F3,			"F3"		},
    { SDLK_F4,			"F4"		},
    { SDLK_F5,			"F5"		},
    { SDLK_F6,			"F6"		},
    { SDLK_F7,			"F7"		},
    { SDLK_F8,			"F8"		},
    { SDLK_F9,			"F9"		},
    { SDLK_F10,			"F10"		},
    { SDLK_F11,			"F11"		},
    { SDLK_F12,			"F12"		},
    { SDLK_F13,			"F13"		},
    { SDLK_F14,			"F14"		},
    { SDLK_F15,			"F15"		},
    { SDLK_HELP,		"Help"		},
    { SDLK_PRINT,		"PrintScreen"	},
    { SDLK_SYSREQ,		"SysReq"	},
    { SDLK_BREAK,		"Break"		},
    { SDLK_MENU,		"Menu"		},
    { SDLK_POWER,		"Power"		},
    { SDLK_EURO,		"Euro"		},
    { SDLK_UNDO,		"Undo"		},

    { SDLK_EX_MOUSE1,		"Mouse 1"	},
    { SDLK_EX_MOUSE2,		"Mouse 2"	},
    { SDLK_EX_MOUSE3,		"Mouse 3"	},
    { SDLK_EX_MOUSE4,		"Mouse 4"	},
    { SDLK_EX_MOUSE4,		"mwheelup"	},
    { SDLK_EX_MOUSE5,		"Mouse 5"	},
    { SDLK_EX_MOUSE5,		"mwheeldown"	},
    { SDLK_EX_MOUSE6,		"Mouse 6"	},
    { SDLK_EX_MOUSE7,		"Mouse 7"	},
    { SDLK_EX_MOUSE8,		"Mouse 8"	},
    { SDLK_EX_MOUSE9,		"Mouse 9"	},
    { SDLK_EX_MOUSE10,		"Mouse 10"	},
    { SDLK_EX_MOUSE11,		"Mouse 11"	},
    { SDLK_EX_MOUSE12,		"Mouse 12"	},
    { SDLK_EX_MOUSE13,		"Mouse 13"	},
    { SDLK_EX_MOUSE14,		"Mouse 14"	},
    { SDLK_EX_MOUSE15,		"Mouse 15"	},

    { SDLK_EX_JOY1,		"Joystick 1"	},
    { SDLK_EX_JOY2,		"Joystick 2"	},
    { SDLK_EX_JOY3,		"Joystick 3"	},
    { SDLK_EX_JOY4,		"Joystick 4"	},
    { SDLK_EX_JOY5,		"Joystick 5"	},
    { SDLK_EX_JOY6,		"Joystick 6"	},
    { SDLK_EX_JOY7,		"Joystick 7"	},
    { SDLK_EX_JOY8,		"Joystick 8"	},
    { SDLK_EX_JOY9,		"Joystick 9"	},
    { SDLK_EX_JOY10,		"Joystick 10"	},
    { SDLK_EX_JOY11,		"Joystick 11"	},
    { SDLK_EX_JOY12,		"Joystick 12"	},
    { SDLK_EX_JOY13,		"Joystick 13"	},
    { SDLK_EX_JOY14,		"Joystick 14"	},
    { SDLK_EX_JOY15,		"Joystick 15"	},
    { SDLK_EX_JOY16,		"Joystick 16"	},
    { SDLK_EX_JOY17,		"Joystick 17"	},
    { SDLK_EX_JOY18,		"Joystick 18"	},
    { SDLK_EX_JOY19,		"Joystick 19"	},
    { SDLK_EX_JOY20,		"Joystick 20"	},
    { SDLK_EX_JOY21,		"Joystick 21"	},
    { SDLK_EX_JOY22,		"Joystick 22"	},
    { SDLK_EX_JOY23,		"Joystick 23"	},
    { SDLK_EX_JOY24,		"Joystick 24"	},
    { SDLK_EX_JOY25,		"Joystick 25"	},
