/*
 * WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY 'generate_var_auto.py' DO NOT EDIT!!!
 */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
  
#include "mem.h"
#include "dbuf.h"
#include "var.h"
#include "net.h"

void
net_pkt_pack_bool(pkt_t *pkt, uint16_t len, int8_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_bool(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_bool(pkt_t *pkt, uint16_t count, int8_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_bool(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_char8(pkt_t *pkt, uint16_t len, int8_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_char8(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_char8(pkt_t *pkt, uint16_t count, int8_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_char8(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_real(pkt_t *pkt, uint16_t len, real *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
#ifdef MATH64
	dbuf_write_double(pkt->dbuf, val[i]);
#else
	dbuf_write_float(pkt->dbuf, val[i]);
#endif
}

void
net_pkt_unpack_real(pkt_t *pkt, uint16_t count, real *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    for (i = 0; i < count; i++)
#ifdef MATH64
        dbuf_read_double(pkt->dbuf, &val[i]);
#else
        dbuf_read_float(pkt->dbuf, &val[i]);
#endif
}

void
net_pkt_pack_int16(pkt_t *pkt, uint16_t len, int16_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_int16(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_int16(pkt_t *pkt, uint16_t count, int16_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_int16(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_int32(pkt_t *pkt, uint16_t len, int32_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_int32(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_int32(pkt_t *pkt, uint16_t count, int32_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_int32(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_int64(pkt_t *pkt, uint16_t len, int64_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_int64(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_int64(pkt_t *pkt, uint16_t count, int64_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_int64(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_int8(pkt_t *pkt, uint16_t len, int8_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_int8(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_int8(pkt_t *pkt, uint16_t count, int8_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_int8(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_str(pkt_t *pkt, uint16_t len, char *val)
{
    dbuf_write_uint16(pkt->dbuf, len);
    dbuf_write_size(pkt->dbuf, val, len);
}

void
net_pkt_unpack_str(pkt_t *pkt, uint16_t *len, char **val)
{
    dbuf_read_uint16(pkt->dbuf, len);

    char *str = mem_malloc0(*len);

    dbuf_read_size(pkt->dbuf, str, *len);

    *val = str;
}

void
net_pkt_pack_uchar8(pkt_t *pkt, uint16_t len, uint8_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_uchar8(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_uchar8(pkt_t *pkt, uint16_t count, uint8_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_uchar8(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_uint16(pkt_t *pkt, uint16_t len, uint16_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_uint16(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_uint16(pkt_t *pkt, uint16_t count, uint16_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_uint16(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_uint32(pkt_t *pkt, uint16_t len, uint32_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_uint32(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_uint32(pkt_t *pkt, uint16_t count, uint32_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_uint32(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_uint64(pkt_t *pkt, uint16_t len, uint64_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_uint64(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_uint64(pkt_t *pkt, uint16_t count, uint64_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_uint64(pkt->dbuf, &val[i]);
}

void
net_pkt_pack_uint8(pkt_t *pkt, uint16_t len, uint8_t *val)
{
    int i;

    dbuf_write_uint16(pkt->dbuf, len);
    for (i = 0; i < len; i++)
        dbuf_write_uint8(pkt->dbuf, val[i]);
}

void
net_pkt_unpack_uint8(pkt_t *pkt, uint16_t count, uint8_t *val)
{
    int i;
    uint16_t len;

    dbuf_read_uint16(pkt->dbuf, &len);
    assert(len == count);
    for (i = 0; i < count; i++)
        dbuf_read_uint8(pkt->dbuf, &val[i]);
}
