
#ifndef _VAR_AUTO_C
#define _VAR_AUTO_C

/*
 * WARNING: THIS FILE IS AUTOMATICALLY GENERATED BY 'generate_var_auto.py' DO NOT EDIT!!!
 */
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
  
#include "mem.h"
#include "dbuf.h"
#include "var.h"
#pragma GCC diagnostic ignored "-Wunused-function"

static void
bool_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%s", (v->b == true) ? "true" : "false");
}

static void
bool_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 1)
        return;

    set8(buf, 0, v->b);

    if (size != NULL)
        *size = 1;
}

static inline var_t *
bools(int8_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_BOOL;
    v->b = val;
    v->size = sizeof(int8_t);
    return v;
}

static inline var_t *
boolh(int8_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_BOOL;
    v->b = val;
    v->size = sizeof(int8_t);
    return v;
}

static void
char8_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%c", v->c8);
}

static void
char8_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 1)
        return;

    set8(buf, 0, v->c8);

    if (size != NULL)
        *size = 1;
}

static inline var_t *
char8s(int8_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_CHAR8;
    v->c8 = val;
    v->size = sizeof(int8_t);
    return v;
}

static inline var_t *
char8h(int8_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_CHAR8;
    v->c8 = val;
    v->size = sizeof(int8_t);
    return v;
}

static void
double_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%f", v->dbl);
}

static void
double_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 8)
        return;

    set64(buf, 0, v->dbl);

    if (size != NULL)
        *size = 8;
}

static inline var_t *
doubles(double val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_DOUBLE;
    v->dbl = val;
    v->size = sizeof(double);
    return v;
}

static inline var_t *
doubleh(double val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_DOUBLE;
    v->dbl = val;
    v->size = sizeof(double);
    return v;
}

static void
float_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%f", v->dbl);
}

static void
float_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 4)
        return;

    set32(buf, 0, v->dbl);

    if (size != NULL)
        *size = 4;
}

static inline var_t *
floats(float val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_FLOAT;
    v->dbl = val;
    v->size = sizeof(float);
    return v;
}

static inline var_t *
floath(float val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_FLOAT;
    v->dbl = val;
    v->size = sizeof(float);
    return v;
}

static void
int16_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%d", v->i16);
}

static void
int16_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 2)
        return;

    set16(buf, 0, v->i16);

    if (size != NULL)
        *size = 2;
}

static inline var_t *
int16s(int16_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_INT16;
    v->i16 = val;
    v->size = sizeof(int16_t);
    return v;
}

static inline var_t *
int16h(int16_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_INT16;
    v->i16 = val;
    v->size = sizeof(int16_t);
    return v;
}

static void
int32_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%d", v->i32);
}

static void
int32_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 4)
        return;

    set32(buf, 0, v->i32);

    if (size != NULL)
        *size = 4;
}

static inline var_t *
int32s(int32_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_INT32;
    v->i32 = val;
    v->size = sizeof(int32_t);
    return v;
}

static inline var_t *
int32h(int32_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_INT32;
    v->i32 = val;
    v->size = sizeof(int32_t);
    return v;
}

static void
int64_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%ld", v->i64);
}

static void
int64_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 8)
        return;

    set64(buf, 0, v->i64);

    if (size != NULL)
        *size = 8;
}

static inline var_t *
int64s(int64_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_INT64;
    v->i64 = val;
    v->size = sizeof(int64_t);
    return v;
}

static inline var_t *
int64h(int64_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_INT64;
    v->i64 = val;
    v->size = sizeof(int64_t);
    return v;
}

static void
int8_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%d", v->i8);
}

static void
int8_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 1)
        return;

    set8(buf, 0, v->i8);

    if (size != NULL)
        *size = 1;
}

static inline var_t *
int8s(int8_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_INT8;
    v->i8 = val;
    v->size = sizeof(int8_t);
    return v;
}

static inline var_t *
int8h(int8_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_INT8;
    v->i8 = val;
    v->size = sizeof(int8_t);
    return v;
}

static void
str_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%s", v->s8);
}

static void
str_to_blob(var_t *v, char *buf, int len, int *size)
{
    int s;
    s = snprintf(buf, len, "%s", (char *)v->ptr);
    if (size != NULL)
        *size = s+1;
}

static inline var_t *
strs(char * val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_STRING;
    v->s8 = val;
    v->size = sizeof(char *);
    return v;
}

static inline var_t *
strh(char * val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_STRING;
    v->s8 = val;
    v->size = sizeof(char *);
    return v;
}

static void
uchar8_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%c", v->uc8);
}

static void
uchar8_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 1)
        return;

    set8(buf, 0, v->uc8);

    if (size != NULL)
        *size = 1;
}

static inline var_t *
uchar8s(uint8_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_UCHAR8;
    v->uc8 = val;
    v->size = sizeof(uint8_t);
    return v;
}

static inline var_t *
uchar8h(uint8_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_UCHAR8;
    v->uc8 = val;
    v->size = sizeof(uint8_t);
    return v;
}

static void
uint16_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%u", v->i16);
}

static void
uint16_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 2)
        return;

    set16(buf, 0, v->i16);

    if (size != NULL)
        *size = 2;
}

static inline var_t *
uint16s(uint16_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_UINT16;
    v->i16 = val;
    v->size = sizeof(uint16_t);
    return v;
}

static inline var_t *
uint16h(uint16_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_UINT16;
    v->i16 = val;
    v->size = sizeof(uint16_t);
    return v;
}

static void
uint32_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%u", v->i32);
}

static void
uint32_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 4)
        return;

    set32(buf, 0, v->i32);

    if (size != NULL)
        *size = 4;
}

static inline var_t *
uint32s(uint32_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_UINT32;
    v->i32 = val;
    v->size = sizeof(uint32_t);
    return v;
}

static inline var_t *
uint32h(uint32_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_UINT32;
    v->i32 = val;
    v->size = sizeof(uint32_t);
    return v;
}

static void
uint64_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%lu", v->i64);
}

static void
uint64_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 8)
        return;

    set64(buf, 0, v->i64);

    if (size != NULL)
        *size = 8;
}

static inline var_t *
uint64s(uint64_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_UINT64;
    v->i64 = val;
    v->size = sizeof(uint64_t);
    return v;
}

static inline var_t *
uint64h(uint64_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_UINT64;
    v->i64 = val;
    v->size = sizeof(uint64_t);
    return v;
}

static void
uint8_to_str(var_t *v, char *buf, int len)
{
    snprintf(buf, len, "%u", v->i8);
}

static void
uint8_to_blob(var_t *v, char *buf, int len, int *size)
{
    if (len < 1)
        return;

    set8(buf, 0, v->i8);

    if (size != NULL)
        *size = 1;
}

static inline var_t *
uint8s(uint8_t val)
{
    var_t *v = alloca(sizeof(var_t));
    v->type = VAR_UINT8;
    v->i8 = val;
    v->size = sizeof(uint8_t);
    return v;
}

static inline var_t *
uint8h(uint8_t val)
{
    var_t *v = malloc(sizeof(var_t));
    v->type = VAR_UINT8;
    v->i8 = val;
    v->size = sizeof(uint8_t);
    return v;
}

#endif
